esphome:
  name: lilygo
  friendly_name: LilyGO
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
  flash_size: 16MB

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  # level: VERBOSE

# Enable Home Assistant API
api:
  # encryption:
    # key: "CGvnxeqFG4C3RGemr8xhvR0VHl6tykTYDsEZHhqeR8Q="

ota:
  password: "51601a4a74335930d1890c15ba49b448"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lilygo"
    password: "(NsdbJE23.Ppn,$"

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: True

captive_portal:
    